Update migimap

diff --git a/migimap b/migimap
--- a/migimap
+++ b/migimap
@@ -14,19 +14,27 @@ if [[ $numCheck =~ ^-?[0-9]+.00$ ]]; then
   echo -e "\nMigrating $numLines email account(s) to Bluehost."
   { while IFS=' ' read host1 user1 pass1 host2 user2 pass2
     do
-      imapsync --ssl1 --ssl2 --useuid --automap --nosyncacls --syncinternaldates --logdir /home/tempeproserve/promig/log --logfile ${user1}.log --pidfile /home/tempeproserve/promig/pid/${user1} --pidfilelocking \
+      imapsync --ssl1 --ssl2 --useuid --automap --nosyncacls --syncinternaldates --tmpdir /home/tempeproserve/promig --logdir /home/tempeproserve/promig/log --logfile ${user1}.log --pidfile /home/tempeproserve/promig/pid/${user1} --pidfilelocking \
           --host1 $host1 --user1 $user1 --password1 $pass1 \
           --host2 $host2 --user2 $user2 --password2 $pass2 $@
     done
   } <<< "$migvars"
-  echo -e "\n====== Results ======"
+  echo -e "\n\t=========================== Results ==========================="
   { while IFS=' ' read host1 user1 pass1 host2 user2 pass2
     do
-      eUser=`echo $user1 | tr [a-z] [A-Z]`
-      results=`egrep 'Start|Final|Detected|Host1 failure|Host2 failure' /home/tempeproserve/promig/log/${user1}.log | sed 's,Exiting with return value 0,Success,g'`
-      results2=`egrep 'Exiting with return value 0' /home/tempeproserve/promig/log/${user1}.log | sed 's,Exiting with return value 0,Success,g'`
-      [ ! -z "$results2" ] && echo -e "${GREEN}${eUser}: ${results2}${SET}" || echo -e "${GREEN}${eUser}:${SET} ${RED}Failure${SET}"
-      echo -e "\t${results}\n"
+      eUser=`echo -e "\t\t\t$user1" | tr [a-z] [A-Z]`
+      results=`egrep 'Start' /home/tempeproserve/promig/log/${user1}.log`
+      results1=`egrep 'Final' /home/tempeproserve/promig/log/${user1}.log`
+      results2=`egrep 'Detected' /home/tempeproserve/promig/log/${user1}.log`
+      results3=`egrep 'Host1 failure' /home/tempeproserve/promig/log/${user1}.log`
+      results4=`egrep 'Host2 failure' /home/tempeproserve/promig/log/${user1}.log`
+      successMes=`egrep 'Exiting with return value 0' /home/tempeproserve/promig/log/${user1}.log | sed 's,Exiting with return value 0,Success,g'`
+      [ ! -z "$successMes" ] && echo -e "${GREEN}${eUser}: ${successMes}${SET}" || echo -e "${GREEN}${eUser}:${SET} ${RED}Failure${SET}"
+      [ ! -z "$results" ] && echo -e "\t${results}"
+      [ ! -z "$results1" ] && echo -e "\t${results1}"
+      [ ! -z "$results2" ] && echo -e "\t${results2}"
+      [ ! -z "$results3" ] && echo -e "\t${results3}"
+      [ ! -z "$results4" ] && echo -e "\t${results4}"
     done
   } <<< "$migvars"
 else
